# fly.toml app configuration file generated for laracasts-blog-mysql on 2023-09-23T20:31:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "laracasts-blog-mysql"
primary_region = "otp"

[build]
  image = "mysql:8.0.32"

[env]
  MYSQL_DATABASE = "laracasts_blog"
  MYSQL_USER = "admin"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"

[[mounts]]
  source = "laracasts_blog_mysql"
  destination = "/data"
